// Generated by `content-sdk codegen` — do not edit by hand.
// Reflects the last published content when this was run; re-run after publishing to refresh.

import type { BlobValue, CategoryDescriptor, ComponentValue, LinkValue, PresentationEnvelope, RichTextValue } from '@ebitex/content-sdk'

/** image (64bc269f-cd6f-4289-9b51-d61a099f58e4@1) */
export type Image = {
  file: BlobValue
  alt: string
}

/** coffee (601d3ff2-7e0a-4c6a-a789-0191d909eec9@2) */
export type Coffee = {
  name: string
  producer?: string
  description?: RichTextValue
  "tasting-notes"?: Array<string>
  price?: number
  "weight-grams"?: number
  image?: ComponentValue<Image>
  origin?: ComponentValue<Origin>
  roast?: CategoryDescriptor
  process?: CategoryDescriptor
}

/** header-content (1adc1dcd-c8bb-4de2-bbb5-6b1a6e4cacc1@1) */
export type HeaderContent = {
  links?: Array<ComponentValue<NavLink>>
}

/** guide (ab59b61d-6d13-4648-8907-4955517a5359@1) */
export type Guide = {
  heading: string
  summary?: string
  equipment?: Array<string>
  "total-time"?: string
  steps?: Array<ComponentValue<GuideStep>>
}

/** statement (622ad278-e1d2-4abe-87dd-ae4143e6bc6d@1) */
export type Statement = {
  heading: string
  standfirst?: string
  body?: RichTextValue
  cta?: LinkValue
  "cta-label"?: string
}

/** origin (734e1bed-64a1-4beb-a536-74d092b18ed7@1) */
export type Origin = {
  name: string
  country?: string
  altitude?: string
  summary?: RichTextValue
  image?: ComponentValue<Image>
  note?: string
}

/** page (50c8cd56-2076-4d95-b161-f863515b281d@2) */
export type Page = {
  title: string
  description?: string
  body?: RichTextValue
  sections?: Array<PresentationEnvelope<CardRail | Statement | FormEmbed>>
}

/** store-list (9c00ccc6-1689-4c97-acd2-9a3c8a94b597@1) */
export type StoreList = {
  heading: string
  intro?: RichTextValue
  stores?: Array<ComponentValue<Store>>
}

/** card-rail (357f3187-67af-4a88-94ef-a53c40b336b2@2) */
export type CardRail = {
  heading: string
  cards?: Array<PresentationEnvelope<Card>>
}

/** footer-content (73c724c1-3f3a-4664-8c0e-33628cf1671d@1) */
export type FooterContent = {
  tagline?: string
  links?: Array<ComponentValue<NavLink>>
}

/** coffee-index (b28b41c6-39e1-4797-a82b-1a37812b677c@1) */
export type CoffeeIndex = {
  heading: string
  intro?: RichTextValue
}

/** guide-index (e9652a91-9359-4bcf-860e-2d13a1564ecb@1) */
export type GuideIndex = {
  heading: string
  intro?: RichTextValue
  guides?: Array<ComponentValue<Guide>>
}

/** nav-link (c8913ea3-c1db-45e9-bb6e-5bfeaeb452ec@1) */
export type NavLink = {
  label: string
  link: LinkValue
}

/** guide-step (dd0f507f-c4d2-49bf-ad34-348ed44c7c98@1) */
export type GuideStep = {
  heading?: string
  body?: RichTextValue
}

/** form-embed (6f8070d2-f83f-4810-aea3-32c50179bbff@1) */
export type FormEmbed = {
  form: string
  title?: string
}

/** store (88384302-c8cd-44c7-a61e-e223619cb94f@1) */
export type Store = {
  name: string
  address?: Array<string>
  hours?: Array<string>
  phone?: string
  map?: LinkValue
}

/** card (535e1bcd-0e37-4923-a5fe-93c720a348af@2) */
export type Card = {
  heading: string
  standfirst?: string
  image?: ComponentValue<Image>
}

/** experience (00000000-0000-0000-0000-000000000283@0) */
export type Experience = {
  name: string
  url?: string
  component?: ComponentValue
  presentation?: PresentationEnvelope
}
